
DROP TABLE IF EXISTS producers CASCADE;

CREATE TABLE IF NOT EXISTS producers(
    producer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
    );

DROP TABLE IF EXISTS movies CASCADE;

CREATE TABLE IF NOT EXISTS movies(
    movie_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    year_of_production INTEGER,
    producer_id INTEGER REFERENCES producers(producer_id)
    );

DROP TABLE IF EXISTS actors CASCADE;

CREATE TABLE IF NOT EXISTS actors(
    actor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
    );

DROP TABLE IF EXISTS movies_actors CASCADE;

CREATE TABLE IF NOT EXISTS movies_actors(
    movie_id INTEGER REFERENCES movies(movie_id) NOT NULL,
    actor_id INTEGER REFERENCES actors(actor_id) NOT NULL
    );

INSERT INTO producers (name) VALUES
                                 ('Warner Bros'),
                                 ('Universal Pictures'),
                                 ('Paramount Pictures'),
                                 ('20th Century Studios'),
                                 ('Sony Pictures'),
                                 ('Walt Disney Pictures');

INSERT INTO movies (title, description, year_of_production, producer_id)
VALUES
    ('The Dark Knight', 'When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.', 2008, 1),
    ('Inception', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', 2010, 1),
    ('Jurassic Park', 'During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run amok.', 1993, 2),
    ('E.T. the Extra-Terrestrial', 'A troubled child summons the courage to help a friendly alien escape Earth and return to his home world.', 1982, 2),
    ('Forrest Gump', 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.', 1994, 3),
    ('Interstellar', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanitys survival.', 2014, 3),
    ('Avatar', 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.', 2009, 4),
    ('X-Men', 'Two mutants come to a private academy for their kind whose resident superhero team must oppose a terrorist organization with similar powers.', 2000, 4),
    ('Spider-Man', 'When bitten by a genetically modified spider, a nerdy, shy, and awkward high school student gains spider-like abilities that he eventually must use to fight evil as a superhero after tragedy befalls his family.', 2002, 5),
    ('Men in Black', 'A police officer joins a secret organization that polices and monitors extraterrestrial interactions on Earth.', 1997, 5),
    ('Frozen', 'When the newly-crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.', 2013, 6),
    ('The Lion King', 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 1994, 6);

INSERT INTO actors (name) VALUES
    ('Christian Bale'),
    ('Heath Ledger'),
    ('Morgan Freeman'),
    ('Leonardo DiCaprio'),
    ('Ellen Page'),
    ('Tom Hardy'),
    ('Sam Neill'),
    ('Laura Dern'),
    ('Drew Barrymore'),
    ('Henry Thomas'),
    ('Tom Hanks'),
    ('Anne Hathaway'),
    ('Sigourney Weaver'),
    ('Sam Worthington'),
    ('Hugh Jackman'),
    ('Patrick Stewart'),
    ('Tobey Maguire'),
    ('Kirsten Dunst'),
    ('Will Smith'),
    ('Tommy Lee Jones'),
    ('Idina Menzel'),
    ('Kristen Bell'),
    ('Matthew Broderick'),
    ('Jeremy Irons');

INSERT INTO movies_actors (movie_id, actor_id)
VALUES
    (1, 1),
    (1, 2),
    (1, 3),
    (2, 1),
    (2, 4),
    (2, 6),
    (3, 7),
    (3, 8),
    (4, 7),
    (4, 9),
    (5, 10),
    (5, 11),
    (6, 10),
    (6, 12),
    (7, 13),
    (7, 14),
    (8, 14),
    (8, 15),
    (9, 16),
    (9, 17),
    (10, 18),
    (10, 19),
    (11, 20),
    (11, 21),
    (12, 22),
    (12, 23);
